### PR TITLE
assumes .png when no extension is specified for images

### PR DESCRIPTION
**Pull request by chkwon**
As I’m not familiar with RUBY, not sure if this is a correct way of
addressing this.

### CODE REVIEW

**Comment by mhartl** [comment]
Thanks for the contribution. PDF output (via LaTeX) requires the full filename (including extension), so there's no way in general to avoid having to specify it. Just make sure to include the full name of your image files and you should be fine.

**Comment by chkwon** [comment]
@mhartl Yes, you are right. In fact, I was using `\DeclareGraphicsExtensions{.jpg}`.

One question. For LaTeX PDF output, `.pdf` images are best, especially when they are vector formats. For the web, `.png` files are used. They are likely produced either by some computer languages (Python, MATLAB, R, Julia, etc.), by screen captures, or by conversion from other bitmap formats. Those `.png` files often involve layers and `RGB` color spaces etc.

I was working with a print book publisher, and they wanted the final PDF output was compatible with `PDF/X-1A`, which requires all images are flattened without layers in CMYK color spaces, etc. It was not easy to work with it, so I ended up with creating high-quality JPG files from PDF and PNG.

Having said that, I have the following needs:
(1) I want the original PDF images for the PDF output for screen.
(2) I want the high-quality JPG images for the PDF output for printing.
These can be easily done by NOT specifying file extensions with `\includegraphics{}` and change `\DeclareGraphicsExtensions{.pdf}` to `\DeclareGraphicsExtensions{.jpg}` in `custom_pdf.sty` depending on my need.

For the HTML version, is there anyway I can adjust the width each image? As far as I understand it just displays its natural width with `max-width` specified in `css`. So, when I create PNG file for HTML, I just create a smaller size PNG file from the PDF format. So, the third need:
(3) I want a smaller-sized PNG images for HTML. 

Perhaps I have to give up one of the above three needs. Any suggestion? 

Right at this moment I am doing:
- No extension specified in `\includegraphic`
- For LaTeX, I have `\DeclareGraphicsExtensions{.pdf}` in `custom_pdf.sty`.
- For HTML / EPUB / MOBI, I modified the code in `html.rb` as shown in this pull request to set `.png` as default when the extension is not specified.

**Comment by mhartl** [comment]
Softcover actually supports this already. If there are files called `foo.pdf` and `foo.png` in the `images/` directory, you can use

```latex
\includegraphics{images/foo.pdf}
```

in your source. The corresponding PNG will automatically be used in the EPUB/MOBI/HTML output.

**Comment by chkwon** [comment]
Can `foo.png` be 4000px wide, but displayed as 300px wide in HTML?

**Pull request closed without merging**
